apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-front
  name: k8s-front
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: k8s-front
  type: LoadBalancer