apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql_db
spec:
  selector:
    matchLabels:
      tier: mysql_db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: mysql_db
    spec:
      containers:
      - image: mysql:8.0
        name: mysql_db
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123456
        - name: MARIADB_USER
          value: user
        - name: MARIADB_USER_PASSWORD
          value: 123456
        - name: MARIADB_DATABASE
          value: 'products'
        ports:
        - containerPort: 3306
          name: mysql_db
        volumeMounts:
        - name: mysql_db
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql_db
        persistentVolumeClaim:
          claimName: mysqldb-data