apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-backend
  name: k8s-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-backend
    spec:
      containers:
      - image: julianalga/k8s-backend:1.0.3
        name: k8s-backend-main
        ports:
        - containerPort: 8080
        resources: {
          requests: {
            cpu: "150m",
            memory: 300Mi
          },
          limits: {
            cpu: "400m",
            memory: "1Gi"
          }
          
          

        }
status: {}
