apiVersion: v1
kind: Service
metadata:
  labels:
    tier: mysqldb
  name: mysqldb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  cluserIp: None
  selector:
    tier: mysqldb
  type: LoadBalancer